fix(http): allow tokens to exceed 20 chars
nmklotas/GitLabApiClient pull request #207
Opened 2021-02-05 09:10 UTC by max-wittig

GitLab allows users of an instance to specify a token prefix since 13.8, which is where this current assumption breaks down

See: https://docs.gitlab.com/ee/user/admin_area/settings/account_and_limit_settings.html#personal-access-token-prefix

2021-02-05 09:19 UTC, mapret commented on src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
> +            if (20 <= authenticationToken.Length || authenticationToken.Length < 64) {
Shouldn't this be a &&-conjunction?

2021-02-05 09:28 UTC, max-wittig commented on src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
> +            if (20 <= authenticationToken.Length || authenticationToken.Length < 64) {
Ahh yes. 🤦  That's true.

2021-02-08 07:24 UTC, max-wittig commented
@mapret Thanks for the initial review! Pipeline should be green now. Would you mind to take another look?

2021-02-17 10:16 UTC, max-wittig commented
@mapret Care to review again? This library is currently not working for people on our instance

2021-02-18 16:15 UTC, mapret commented
@max-wittig Looks good to me, but I am not a maintainer of this project, I am just the one who opened the related issue on our internal GitLab 😉.

2021-02-25 07:45 UTC, max-wittig commented
@jetersen @nmklotas Would you mind to take a look?

2021-02-25 07:48 UTC, jetersen requested changes
I think it would be better to distinguish between bearer token and PAT via two properties.

2021-02-28 20:33 UTC, max-wittig commented
@jetersen thanks for the review. What do you mean by `properties`? Attributes that the user specifies? I'm not really into C# and this was ment as a bit of a quick fix so I'm not too familiar with all the details of the language.

2021-03-24 13:01 UTC, wwwjon commented
I came across this pull request because I encountered the same issue and I'm very interested that this issues is fixed as soon as possible. So I would like to help, but unfortunately I don't understand either exactly how @jetersen imagined it with properties.

@jetersen Could you explain this in more detail?

2021-04-26 11:47 UTC, max-wittig commented
@jetersen Using switch again now. Could you please take another look?

2021-08-02 08:22 UTC, fgreinacher commented
@jetersen @nmklotas Mind having a look at this? We're also running in the underlying issue 😀

2021-08-02 11:04 UTC, jetersen approved these changes

2021-08-02 11:04 UTC, merged